name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout libxposed/api
        uses: actions/checkout@v4
        with:
          repository: libxposed/api
          path: libxposed/api
          fetch-depth: 0

      - name: Checkout libxposed/service
        uses: actions/checkout@v4
        with:
          repository: libxposed/service
          path: libxposed/service
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'

      - name: Build sdk
        id: buildsdk
        run: |
          # gradle properties
          mkdir -p ~/.gradle
          echo 'org.gradle.caching=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.parallel=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC' >> ~/.gradle/gradle.properties
          echo 'android.native.buildOutput=verbose' >> ~/.gradle/gradle.properties
          # build dependencies
          cd libxposed/api && ./gradlew publishToMavenLocal && cd ../..
          cd libxposed/service && ./gradlew publishToMavenLocal && cd ../..
          # build
          chmod +x ./gradlew
          ./gradlew build
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'

      - name: Build app
        id: buildapp
        run: |
          chmod +x ./gradlew
          ./gradlew build
      
      - name: Upload release
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_apk.outputs.release }}
          path: "app/build/outputs/apk/release/*-release.apk"
